### PR TITLE
wip: Hackathon XXIII -- Account MFE login & registration

### PR DESCRIPTION
**Pull request by kdmccormick**

### CODE REVIEW

**Comment by kdmccormick** [comment]
@waheedahmed It's great to hear that your team has picked up our hackathon work! We're excited to see it come to fruition :smiley:

**Comment by waheedahmed** [comment]
Thank you @kdmccormick, we are also excited to work on this new logistration MFE.

**Comment by kdmccormick** [comment]
Hey @waheedahmed -- Are we good to close this now that http://github.com/edx/frontend-app-logistration exists?

**Comment by waheedahmed** [comment]
Hi @kdmccormick, yes we are good to close this out now.

**Pull request closed without merging**
