### PR TITLE
Update openedx.yaml

### PR DESCRIPTION
**Pull request by adzuci**

### CODE REVIEW

**Review by kdmccormick — CHANGES_REQUESTED** [review]
The [owner key is obselete](https://open-edx-proposals.readthedocs.io/en/latest/oep-0002-bp-repo-metadata.html#obsolete-keys) since [the spreadsheet](https://docs.google.com/spreadsheets/d/1qpWfbPYLSaE_deaumWSEZfz91CshWd3v3B7xhOk5M4U/edit) became the source of truth; could you just delete the line altogether?

(but yes, we own this currently :)

**Review by kdmccormick — APPROVED** [review]
LGTM; just add some detail to your commit message when you squash+merge.

**Comment by kdmccormick** [comment]
Thanks for the update!

**Comment by stvstnfrd** [comment]
@adzuci @kdmccormick Is this good to merge?

**Comment by kdmccormick** [comment]
@stvstnfrd Still looks good to me 👍🏻

**Pull request merged**
